# Generated by Django 2.0 on 2020-03-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0019_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrobj',
            name='currstatus',
            field=models.ForeignKey(blank=True, default=0, help_text='последние две цифры в коде', null=True, on_delete=django.db.models.deletion.CASCADE, to='fias.CurentSt', verbose_name='Статус актуальности КЛАДР 4'),
        ),
    ]
