# Generated by Django 2.0 on 2020-03-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0019_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stead',
            name='number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер земельного участка'),
        ),
    ]
