# Generated by Django 2.0 on 2020-03-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0020_auto_20200326_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrobj',
            name='formalname',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Формализованное наименование'),
        ),
        migrations.AlterField(
            model_name='addrobj',
            name='offname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Официальное наименование'),
        ),
    ]
