# Generated by Django 2.0 on 2020-04-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0024_normdoc_docimgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normdoc',
            name='docnum',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер документа'),
        ),
    ]
